"""empty message

Revision ID: 563f9510e178
Revises: 98fa8cb77c8f
Create Date: 2024-01-26 01:18:28.602684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563f9510e178'
down_revision = '98fa8cb77c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_table', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_table', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
